set nocompatible
filetype on
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" Editor enhancements
Bundle 'commentary.vim'
Bundle 'delimitMate.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'
Bundle 'ervandew/supertab'
Bundle 'Lokaltog/vim-easymotion'

" Programming languages and frameworks
Bundle 'VimClojure'
Bundle 'vim-coffee-script'
Bundle 'html5.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-rails'
Bundle 'vim-ruby/vim-ruby'

" Local bundles; source it here or plugins don't get loaded
if filereadable($HOME . "/.vimrc.local_vundles")
  source ~/.vimrc.local_vundles
endif

filetype plugin indent on

set modelines=0

set autoindent
set smartindent
set showmatch
set showmode
set showcmd
set cursorline
set number
set ruler

set list
set listchars=tab:▸\ ,eol:¬

set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set wrap
set textwidth=79
set formatoptions=qrn1
if exists("&colorcolumn")
    set colorcolumn=85
endif

if exists("&autochdir")
    set autochdir
endif

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap ; :

" Removes trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Toggle NERDTree
nnoremap <leader>t :NERDTreeToggle<CR>

" Autosave on window focus loss
au FocusLost * :wa

set guifont=Bitstream\ Vera\ Sans\ Mono:h14
" Hide toolbar
set guioptions-=T

:syntax enable

set t_Co=256
set background=dark
colorscheme solarized

" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
