set encoding=utf8

call plug#begin('~/.vim/plugged')

Plug 'noahfrederick/vim-neovim-defaults'
Plug 'sheerun/vim-polyglot'

if filereadable($HOME . "/.vimrc.local_plugins")
  source ~/.vimrc.local_plugins
endif

call plug#end()

filetype on

set modelines=0

set showmode
set smartindent
set showmatch
set cursorline
set number

set backspace=indent,eol,start

set list
set listchars=tab:▸\ ,eol:¬

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set textwidth=79
" set colorcolumn=+6

set scrolloff=3

set mouse=a

set wildmode=list:longest,full

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap ; :

" Removes trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
