set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

" Editor enhancements
Bundle 'ack.vim'
Bundle 'commentary.vim'
Bundle 'delimitMate.vim'
Bundle 'altercation/vim-colors-solarized'

" Programming languages and frameworks
Bundle 'VimClojure'
Bundle 'rails.vim'
Bundle 'html5.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-haml'
Bundle 'vim-ruby/vim-ruby'

filetype plugin indent on

set modelines=0

set autoindent
set smartindent
set showmatch
set showmode
set showcmd
set cursorline
set number
set ruler

set list
set listchars=tab:▸\ ,eol:¬

set smarttab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set wrap
set textwidth=79
set formatoptions=qrn1
"set colorcolumn=85

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap ; :

nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

au FocusLost * :wa

set guifont=Menlo:h12
set go-=T
if has('gui_running')
    set background=dark
else
    set background=light
endif
"let g:molokai_original = 1
set t_Co=256
colorscheme solarized

